apiVersion: v1
kind: Namespace
metadata:
  name: test1

---
apiVersion: v1
kind: Namespace
metadata:
  name: test2
  labels:
    ns: test2

---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-1
  namespace: test1
  labels:
    app: test1
spec:
  containers:
    - name: nginx
      image: nginx:1.12-alpine

---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-2
  namespace: test2
  labels:
    app: test2
spec:
  containers:
    - name: nginx
      image: nginx:1.12-alpine
